//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 10-12-2021 02:28:27 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ReporteriaMovistar.Domain.Models.Entities
{
    public partial class EquipoMovimientoEntity {

        public virtual int Id { get; set; }

        public virtual DateTime Fecha { get; set; }

        public virtual int EquipoId { get; set; }

        public virtual int EtapaOrigenId { get; set; }

        public virtual int EtapaDestinoId { get; set; }

        public virtual int OperarioId { get; set; }

        public virtual int? OperarioDevolucionId { get; set; }

        public virtual string Observacion { get; set; }

        public virtual DateTime FechaCreacionRegistro { get; set; }

        public virtual string UsuarioCreacionRegistro { get; set; }

        public virtual DateTime? FechaModificacionRegistro { get; set; }

        public virtual string UsuarioModificacionRegistro { get; set; }

        public virtual DateTime? FechaEliminacionRegistro { get; set; }

        public virtual string UsuarioEliminacionRegistro { get; set; }

        public virtual bool Activo { get; set; }

        public virtual EtapaEntity EtapaEntity_EtapaOrigenId { get; set; }

        public virtual EtapaEntity EtapaEntity_EtapaDestinoId { get; set; }

        public virtual EquipoEntity EquipoEntity { get; set; }

        public virtual OperarioEntity OperarioEntity_OperarioId { get; set; }

        public virtual OperarioEntity OperarioEntity_OperarioDevolucionId { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
