//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 10-12-2021 02:28:27 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ReporteriaMovistar.Domain.Models.Entities
{
    public partial class TempDespachoCsvEntity {

        public virtual int Id { get; set; }

        public virtual string Esn { get; set; }

        public virtual DateTime Fecha { get; set; }

        public virtual string Guia { get; set; }

        public virtual string EstadoDespacho { get; set; }

        public virtual string Operario { get; set; }

        public virtual int Caja { get; set; }

        public virtual int Pallet { get; set; }

        public virtual string EstadoFuentePoder { get; set; }

        public virtual string EstadoUtp { get; set; }

        public virtual string EstadoControlRemoto { get; set; }

        public virtual string EstadoHdmi { get; set; }

        public virtual string EstadoRca { get; set; }

        public virtual bool Pintura { get; set; }

        public virtual string Derivada { get; set; }

        public virtual bool ProcesoFinalizado { get; set; }

        public virtual int? EquipoId { get; set; }

        public virtual DateTime FechaCreacionRegistro { get; set; }

        public virtual string UsuarioCreacionRegistro { get; set; }

        public virtual bool CargaExitosa { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
