//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class ApiUserEntityConverter
    {

        public static ApiUserEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ApiUserEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new ApiUserEntityDto();

            // Properties
            target.Id = source.Id;
            target.KeyHash = source.KeyHash;
            target.Comments = source.Comments;
            target.CreatedAt = source.CreatedAt;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedAt = source.ModifiedAt;
            target.ModifiedBy = source.ModifiedBy;
            target.DeactivatedAt = source.DeactivatedAt;
            target.DeactivatedBy = source.DeactivatedBy;
            target.DeactivatedReason = source.DeactivatedReason;
            target.Active = source.Active;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity ToEntity(this ApiUserEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity();

            // Properties
            target.Id = source.Id;
            target.KeyHash = source.KeyHash;
            target.Comments = source.Comments;
            target.CreatedAt = source.CreatedAt;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedAt = source.ModifiedAt;
            target.ModifiedBy = source.ModifiedBy;
            target.DeactivatedAt = source.DeactivatedAt;
            target.DeactivatedBy = source.DeactivatedBy;
            target.DeactivatedReason = source.DeactivatedReason;
            target.Active = source.Active;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ApiUserEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ApiUserEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity> ToEntities(this IEnumerable<ApiUserEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity source, ApiUserEntityDto target);

        static partial void OnEntityCreating(ApiUserEntityDto source, ReporteriaMovistar.Domain.Models.Entities.ApiUserEntity target);

    }

}
