//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class IdentityUserOperationLogEntityConverter
    {

        public static IdentityUserOperationLogEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static IdentityUserOperationLogEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new IdentityUserOperationLogEntityDto();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.Detail = source.Detail;
            target.CreatedAt = source.CreatedAt;

            // Navigation Properties
            if (level > 0) {
              target.IdentityUserEntity = source.IdentityUserEntity.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity ToEntity(this IdentityUserOperationLogEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.Detail = source.Detail;
            target.CreatedAt = source.CreatedAt;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<IdentityUserOperationLogEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<IdentityUserOperationLogEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity> ToEntities(this IEnumerable<IdentityUserOperationLogEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity source, IdentityUserOperationLogEntityDto target);

        static partial void OnEntityCreating(IdentityUserOperationLogEntityDto source, ReporteriaMovistar.Domain.Models.Entities.IdentityUserOperationLogEntity target);

    }

}
