//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class IdentityRoleClaimEntityConverter
    {

        public static IdentityRoleClaimEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static IdentityRoleClaimEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new IdentityRoleClaimEntityDto();

            // Properties
            target.Id = source.Id;
            target.CreatedAt = source.CreatedAt;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedAt = source.ModifiedAt;
            target.ModifiedBy = source.ModifiedBy;
            target.DeactivatedAt = source.DeactivatedAt;
            target.DeactivatedBy = source.DeactivatedBy;
            target.RoleId = source.RoleId;
            target.ClaimType = source.ClaimType;
            target.ClaimValue = source.ClaimValue;

            // Navigation Properties
            if (level > 0) {
              target.IdentityRoleEntity = source.IdentityRoleEntity.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity ToEntity(this IdentityRoleClaimEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity();

            // Properties
            target.Id = source.Id;
            target.CreatedAt = source.CreatedAt;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedAt = source.ModifiedAt;
            target.ModifiedBy = source.ModifiedBy;
            target.DeactivatedAt = source.DeactivatedAt;
            target.DeactivatedBy = source.DeactivatedBy;
            target.RoleId = source.RoleId;
            target.ClaimType = source.ClaimType;
            target.ClaimValue = source.ClaimValue;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<IdentityRoleClaimEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<IdentityRoleClaimEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity> ToEntities(this IEnumerable<IdentityRoleClaimEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity source, IdentityRoleClaimEntityDto target);

        static partial void OnEntityCreating(IdentityRoleClaimEntityDto source, ReporteriaMovistar.Domain.Models.Entities.IdentityRoleClaimEntity target);

    }

}
