//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class OperarioEntityConverter
    {

        public static OperarioEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.OperarioEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static OperarioEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.OperarioEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new OperarioEntityDto();

            // Properties
            target.Id = source.Id;
            target.Nombre = source.Nombre;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // Navigation Properties
            if (level > 0) {
              target.EquipoMovimientoEntities_OperarioId = source.EquipoMovimientoEntities_OperarioId.ToDtosWithRelated(level - 1);
              target.EquipoMovimientoEntities_OperarioDevolucionId = source.EquipoMovimientoEntities_OperarioDevolucionId.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.OperarioEntity ToEntity(this OperarioEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.OperarioEntity();

            // Properties
            target.Id = source.Id;
            target.Nombre = source.Nombre;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<OperarioEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.OperarioEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<OperarioEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.OperarioEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.OperarioEntity> ToEntities(this IEnumerable<OperarioEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.OperarioEntity source, OperarioEntityDto target);

        static partial void OnEntityCreating(OperarioEntityDto source, ReporteriaMovistar.Domain.Models.Entities.OperarioEntity target);

    }

}
