//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class PronosticoEntityConverter
    {

        public static PronosticoEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static PronosticoEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new PronosticoEntityDto();

            // Properties
            target.Id = source.Id;
            target.Mes = source.Mes;
            target.Ano = source.Ano;
            target.TecnologiaId = source.TecnologiaId;
            target.Estimacion = source.Estimacion;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // Navigation Properties
            if (level > 0) {
              target.EquipoTecnologiaEntity = source.EquipoTecnologiaEntity.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity ToEntity(this PronosticoEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity();

            // Properties
            target.Id = source.Id;
            target.Mes = source.Mes;
            target.Ano = source.Ano;
            target.TecnologiaId = source.TecnologiaId;
            target.Estimacion = source.Estimacion;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<PronosticoEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<PronosticoEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity> ToEntities(this IEnumerable<PronosticoEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity source, PronosticoEntityDto target);

        static partial void OnEntityCreating(PronosticoEntityDto source, ReporteriaMovistar.Domain.Models.Entities.PronosticoEntity target);

    }

}
