//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class SPSeguimientoDespachoEntityResultConverter
    {

        public static SPSeguimientoDespachoEntityResultDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static SPSeguimientoDespachoEntityResultDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult source, int level)
        {
            if (source == null)
              return null;

            var target = new SPSeguimientoDespachoEntityResultDto();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.Esn = source.Esn;
            target.Guia = source.Guia;
            target.EstadoDespacho = source.EstadoDespacho;
            target.Caja = source.Caja;
            target.Pallet = source.Pallet;
            target.Derivada = source.Derivada;
            target.EstadoUtp = source.EstadoUtp;
            target.EstadoFuentePoder = source.EstadoFuentePoder;
            target.EstadoControlRemoto = source.EstadoControlRemoto;
            target.EstadoHdmi = source.EstadoHdmi;
            target.EstadoRca = source.EstadoRca;
            target.Pintura = source.Pintura;
            target.ControlCalidad = source.ControlCalidad;
            target.ProcesoFinalizado = source.ProcesoFinalizado;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult ToEntity(this SPSeguimientoDespachoEntityResultDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.Esn = source.Esn;
            target.Guia = source.Guia;
            target.EstadoDespacho = source.EstadoDespacho;
            target.Caja = source.Caja;
            target.Pallet = source.Pallet;
            target.Derivada = source.Derivada;
            target.EstadoUtp = source.EstadoUtp;
            target.EstadoFuentePoder = source.EstadoFuentePoder;
            target.EstadoControlRemoto = source.EstadoControlRemoto;
            target.EstadoHdmi = source.EstadoHdmi;
            target.EstadoRca = source.EstadoRca;
            target.Pintura = source.Pintura;
            target.ControlCalidad = source.ControlCalidad;
            target.ProcesoFinalizado = source.ProcesoFinalizado;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<SPSeguimientoDespachoEntityResultDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<SPSeguimientoDespachoEntityResultDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult> ToEntities(this IEnumerable<SPSeguimientoDespachoEntityResultDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult source, SPSeguimientoDespachoEntityResultDto target);

        static partial void OnEntityCreating(SPSeguimientoDespachoEntityResultDto source, ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoDespachoEntityResult target);

    }

}
