//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class SPSeguimientoUltimoMovimientoEntityResultConverter
    {

        public static SPSeguimientoUltimoMovimientoEntityResultDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static SPSeguimientoUltimoMovimientoEntityResultDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult source, int level)
        {
            if (source == null)
              return null;

            var target = new SPSeguimientoUltimoMovimientoEntityResultDto();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.Esn = source.Esn;
            target.Origen = source.Origen;
            target.Destino = source.Destino;
            target.Operario = source.Operario;
            target.OperarioDevolucion = source.OperarioDevolucion;
            target.Observacion = source.Observacion;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult ToEntity(this SPSeguimientoUltimoMovimientoEntityResultDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.Esn = source.Esn;
            target.Origen = source.Origen;
            target.Destino = source.Destino;
            target.Operario = source.Operario;
            target.OperarioDevolucion = source.OperarioDevolucion;
            target.Observacion = source.Observacion;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<SPSeguimientoUltimoMovimientoEntityResultDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<SPSeguimientoUltimoMovimientoEntityResultDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult> ToEntities(this IEnumerable<SPSeguimientoUltimoMovimientoEntityResultDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult source, SPSeguimientoUltimoMovimientoEntityResultDto target);

        static partial void OnEntityCreating(SPSeguimientoUltimoMovimientoEntityResultDto source, ReporteriaMovistar.Domain.Models.Entities.SPSeguimientoUltimoMovimientoEntityResult target);

    }

}
