//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: jue. 11 nov. 2021 9:55:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class VWDetalleMovimientoEquipoPowerBiEntityConverter
    {

        public static VWDetalleMovimientoEquipoPowerBiEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VWDetalleMovimientoEquipoPowerBiEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new VWDetalleMovimientoEquipoPowerBiEntityDto();

            // Properties
            target.RecepcionId = source.RecepcionId;
            target.MarcaEquipo = source.MarcaEquipo;
            target.ModeloEquipo = source.ModeloEquipo;
            target.ColorEquipo = source.ColorEquipo;
            target.TecnologiaEquipo = source.TecnologiaEquipo;
            target.FechaRecepcion = source.FechaRecepcion;
            target.FechaMovimiento = source.FechaMovimiento;
            target.EtapaOrigen = source.EtapaOrigen;
            target.ZonaOrigen = source.ZonaOrigen;
            target.EtapaDestino = source.EtapaDestino;
            target.ZonaDestino = source.ZonaDestino;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity ToEntity(this VWDetalleMovimientoEquipoPowerBiEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity();

            // Properties
            target.RecepcionId = source.RecepcionId;
            target.MarcaEquipo = source.MarcaEquipo;
            target.ModeloEquipo = source.ModeloEquipo;
            target.ColorEquipo = source.ColorEquipo;
            target.TecnologiaEquipo = source.TecnologiaEquipo;
            target.FechaRecepcion = source.FechaRecepcion;
            target.FechaMovimiento = source.FechaMovimiento;
            target.EtapaOrigen = source.EtapaOrigen;
            target.ZonaOrigen = source.ZonaOrigen;
            target.EtapaDestino = source.EtapaDestino;
            target.ZonaDestino = source.ZonaDestino;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VWDetalleMovimientoEquipoPowerBiEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VWDetalleMovimientoEquipoPowerBiEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity> ToEntities(this IEnumerable<VWDetalleMovimientoEquipoPowerBiEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity source, VWDetalleMovimientoEquipoPowerBiEntityDto target);

        static partial void OnEntityCreating(VWDetalleMovimientoEquipoPowerBiEntityDto source, ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity target);

    }

}
