//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public static partial class VWMovimientoEquipoEntityConverter
    {

        public static VWMovimientoEquipoEntityDto ToDto(this ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VWMovimientoEquipoEntityDto ToDtoWithRelated(this ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new VWMovimientoEquipoEntityDto();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.Esn = source.Esn;
            target.Marca = source.Marca;
            target.Modelo = source.Modelo;
            target.Color = source.Color;
            target.OrigenId = source.OrigenId;
            target.Origen = source.Origen;
            target.DestinoId = source.DestinoId;
            target.Destino = source.Destino;
            target.Operario = source.Operario;
            target.OperarioDevolucion = source.OperarioDevolucion;
            target.Observacion = source.Observacion;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity ToEntity(this VWMovimientoEquipoEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.Esn = source.Esn;
            target.Marca = source.Marca;
            target.Modelo = source.Modelo;
            target.Color = source.Color;
            target.OrigenId = source.OrigenId;
            target.Origen = source.Origen;
            target.DestinoId = source.DestinoId;
            target.Destino = source.Destino;
            target.Operario = source.Operario;
            target.OperarioDevolucion = source.OperarioDevolucion;
            target.Observacion = source.Observacion;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VWMovimientoEquipoEntityDto> ToDtos(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VWMovimientoEquipoEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity> ToEntities(this IEnumerable<VWMovimientoEquipoEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity source, VWMovimientoEquipoEntityDto target);

        static partial void OnEntityCreating(VWMovimientoEquipoEntityDto source, ReporteriaMovistar.Domain.Models.Entities.VWMovimientoEquipoEntity target);

    }

}
