//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 03-12-2021 09:23:53 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using ReporteriaMovistar.Clients.ApiPowerBi.Models;

namespace ReporteriaMovistar.Clients.ApiPowerBi.DataProviders
{

    public partial class ReporteriaMovistarDbContext : DbContext
    {

        public ReporteriaMovistarDbContext(DbContextOptions<ReporteriaMovistarDbContext> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(@"Data Source=10.51.128.248;Initial Catalog=ReporteriaMovistar_Test;Integrated Security=False;Persist Security Info=True;User ID=cellstaradm;Password=cellstaradm");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<ApiUserEntity> ApiUserEntities
        {
            get;
            set;
        }

        public virtual DbSet<VWDetallePronosticoEquipoPowerBiEntity> VWDetallePronosticoEquipoPowerBiEntities
        {
            get;
            set;
        }

        public virtual DbSet<VWHistorialMovimientoEquipoPowerBiEntity> VWHistorialMovimientoEquipoPowerBiEntities
        {
            get;
            set;
        }

        public virtual DbSet<VWRechazoLimpiezaPowerBiEntity> VWRechazoLimpiezaPowerBiEntities
        {
            get;
            set;
        }

        public virtual DbSet<VWUltimoEstadoEquipoPowerBiEntity> VWUltimoEstadoEquipoPowerBiEntities
        {
            get;
            set;
        }

        public virtual DbSet<VWEstadoLimpiezaPowerBiEntity> VWEstadoLimpiezaPowerBiEntities
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.ApiUserEntityMapping(modelBuilder);
            this.CustomizeApiUserEntityMapping(modelBuilder);

            this.VWDetallePronosticoEquipoPowerBiEntityMapping(modelBuilder);
            this.CustomizeVWDetallePronosticoEquipoPowerBiEntityMapping(modelBuilder);

            this.VWHistorialMovimientoEquipoPowerBiEntityMapping(modelBuilder);
            this.CustomizeVWHistorialMovimientoEquipoPowerBiEntityMapping(modelBuilder);

            this.VWRechazoLimpiezaPowerBiEntityMapping(modelBuilder);
            this.CustomizeVWRechazoLimpiezaPowerBiEntityMapping(modelBuilder);

            this.VWUltimoEstadoEquipoPowerBiEntityMapping(modelBuilder);
            this.CustomizeVWUltimoEstadoEquipoPowerBiEntityMapping(modelBuilder);

            this.VWEstadoLimpiezaPowerBiEntityMapping(modelBuilder);
            this.CustomizeVWEstadoLimpiezaPowerBiEntityMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region ApiUserEntity Mapping

        private void ApiUserEntityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ApiUserEntity>().ToTable(@"ApiUser", @"dbo");
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.KeyHash).HasColumnName(@"KeyHash").HasColumnType(@"varchar(max)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.Comments).HasColumnName(@"Comments").HasColumnType(@"varchar(200)").ValueGeneratedNever().HasMaxLength(200);
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType(@"varchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType(@"varchar(256)").ValueGeneratedNever().HasMaxLength(256);
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.DeactivatedAt).HasColumnName(@"DeactivatedAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.DeactivatedBy).HasColumnName(@"DeactivatedBy").HasColumnType(@"varchar(256)").ValueGeneratedNever().HasMaxLength(256);
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.DeactivatedReason).HasColumnName(@"DeactivatedReason").HasColumnType(@"varchar(200)").ValueGeneratedNever().HasMaxLength(200);
            modelBuilder.Entity<ApiUserEntity>().Property(x => x.Active).HasColumnName(@"Active").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ApiUserEntity>().HasKey(@"Id");
        }

        partial void CustomizeApiUserEntityMapping(ModelBuilder modelBuilder);

        #endregion

        #region VWDetallePronosticoEquipoPowerBiEntity Mapping

        private void VWDetallePronosticoEquipoPowerBiEntityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().HasNoKey();
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().ToView(@"VW_DetallePronosticoEquipoPowerBi", @"dbo");
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.Periodo).HasColumnName(@"Periodo").HasColumnType(@"varchar(7)").ValueGeneratedNever().HasMaxLength(7);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.Pronostico).HasColumnName(@"Pronostico").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.Tecnologia).HasColumnName(@"Tecnologia").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadDiagnostico).HasColumnName(@"CantidadDiagnostico").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadAceptados).HasColumnName(@"CantidadAceptados").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadRechazados).HasColumnName(@"CantidadRechazados").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadPendientes).HasColumnName(@"CantidadPendientes").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadScrap).HasColumnName(@"CantidadScrap").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadRemozados).HasColumnName(@"CantidadRemozados").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWDetallePronosticoEquipoPowerBiEntity>().Property(x => x.CantidadDespachados).HasColumnName(@"CantidadDespachados").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
        }

        partial void CustomizeVWDetallePronosticoEquipoPowerBiEntityMapping(ModelBuilder modelBuilder);

        #endregion

        #region VWHistorialMovimientoEquipoPowerBiEntity Mapping

        private void VWHistorialMovimientoEquipoPowerBiEntityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().HasNoKey();
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().ToView(@"VW_HistorialMovimientoEquipoPowerBi", @"dbo");
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Esn).HasColumnName(@"Esn").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.FechaRecepcion).HasColumnName(@"FechaRecepcion").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Marca).HasColumnName(@"Marca").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Modelo).HasColumnName(@"Modelo").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Color).HasColumnName(@"Color").HasColumnType(@"varchar(30)").IsRequired().ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Tipo).HasColumnName(@"Tipo").HasColumnType(@"varchar(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Subtipo).HasColumnName(@"Subtipo").HasColumnType(@"varchar(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.NumeroReferencia).HasColumnName(@"NumeroReferencia").HasColumnType(@"varchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Categoria).HasColumnName(@"Categoria").HasColumnType(@"varchar(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Subcategoria).HasColumnName(@"Subcategoria").HasColumnType(@"varchar(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Operario).HasColumnName(@"Operario").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Origen).HasColumnName(@"Origen").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Destino).HasColumnName(@"Destino").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Observacion).HasColumnName(@"Observacion").HasColumnType(@"varchar(200)").ValueGeneratedNever().HasMaxLength(200);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Caja).HasColumnName(@"Caja").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Pallet).HasColumnName(@"Pallet").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.TipoConfiguracion).HasColumnName(@"TipoConfiguracion").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.DetalleTipoConfiguracion).HasColumnName(@"DetalleTipoConfiguracion").HasColumnType(@"varchar(200)").ValueGeneratedNever().HasMaxLength(200);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Tecnologia).HasColumnName(@"Tecnologia").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.ProcesoFinalizado).HasColumnName(@"ProcesoFinalizado").HasColumnType(@"varchar(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Derivada).HasColumnName(@"Derivada").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Guia).HasColumnName(@"Guia").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Pintura).HasColumnName(@"Pintura").HasColumnType(@"varchar(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.ControlRemoto).HasColumnName(@"ControlRemoto").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.FuentePoder).HasColumnName(@"FuentePoder").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Hdmi).HasColumnName(@"Hdmi").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Rca).HasColumnName(@"Rca").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.Utp).HasColumnName(@"Utp").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWHistorialMovimientoEquipoPowerBiEntity>().Property(x => x.EstadoDespacho).HasColumnName(@"EstadoDespacho").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
        }

        partial void CustomizeVWHistorialMovimientoEquipoPowerBiEntityMapping(ModelBuilder modelBuilder);

        #endregion

        #region VWRechazoLimpiezaPowerBiEntity Mapping

        private void VWRechazoLimpiezaPowerBiEntityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().HasNoKey();
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().ToView(@"VW_RechazoLimpiezaPowerBi", @"dbo");
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().Property(x => x.Esn).HasColumnName(@"Esn").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().Property(x => x.Origen).HasColumnName(@"Origen").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().Property(x => x.Destino).HasColumnName(@"Destino").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWRechazoLimpiezaPowerBiEntity>().Property(x => x.Operario).HasColumnName(@"Operario").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
        }

        partial void CustomizeVWRechazoLimpiezaPowerBiEntityMapping(ModelBuilder modelBuilder);

        #endregion

        #region VWUltimoEstadoEquipoPowerBiEntity Mapping

        private void VWUltimoEstadoEquipoPowerBiEntityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().HasNoKey();
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().ToView(@"VW_UltimoEstadoEquipoPowerBi", @"dbo");
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Esn).HasColumnName(@"Esn").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.FechaRecepcion).HasColumnName(@"FechaRecepcion").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Marca).HasColumnName(@"Marca").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Modelo).HasColumnName(@"Modelo").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Operario).HasColumnName(@"Operario").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Origen).HasColumnName(@"Origen").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Destino).HasColumnName(@"Destino").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Observacion).HasColumnName(@"Observacion").HasColumnType(@"varchar(200)").ValueGeneratedNever().HasMaxLength(200);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Caja).HasColumnName(@"Caja").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Pallet).HasColumnName(@"Pallet").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.TipoConfiguracion).HasColumnName(@"TipoConfiguracion").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.DetalleTipoConfiguracion).HasColumnName(@"DetalleTipoConfiguracion").HasColumnType(@"varchar(200)").IsRequired().ValueGeneratedNever().HasMaxLength(200);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Tecnologia).HasColumnName(@"Tecnologia").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.ProcesoFinalizado).HasColumnName(@"ProcesoFinalizado").HasColumnType(@"varchar(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Derivada).HasColumnName(@"Derivada").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Guia).HasColumnName(@"Guia").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Pintura).HasColumnName(@"Pintura").HasColumnType(@"varchar(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.ControlRemoto).HasColumnName(@"ControlRemoto").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.FuentePoder).HasColumnName(@"FuentePoder").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Hdmi).HasColumnName(@"Hdmi").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Rca).HasColumnName(@"Rca").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.Utp).HasColumnName(@"Utp").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWUltimoEstadoEquipoPowerBiEntity>().Property(x => x.EstadoDespacho).HasColumnName(@"EstadoDespacho").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
        }

        partial void CustomizeVWUltimoEstadoEquipoPowerBiEntityMapping(ModelBuilder modelBuilder);

        #endregion

        #region VWEstadoLimpiezaPowerBiEntity Mapping

        private void VWEstadoLimpiezaPowerBiEntityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().HasNoKey();
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().ToView(@"VW_EstadoLimpiezaPowerBi", @"dbo");
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().Property(x => x.Esn).HasColumnName(@"Esn").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().Property(x => x.FechaLimpieza).HasColumnName(@"FechaLimpieza").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().Property(x => x.OperarioLimpieza).HasColumnName(@"OperarioLimpieza").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().Property(x => x.FechaRechazo).HasColumnName(@"FechaRechazo").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().Property(x => x.OperarioRechazo).HasColumnName(@"OperarioRechazo").HasColumnType(@"varchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VWEstadoLimpiezaPowerBiEntity>().Property(x => x.Rechazado).HasColumnName(@"Rechazado").HasColumnType(@"varchar(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
        }

        partial void CustomizeVWEstadoLimpiezaPowerBiEntityMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
