//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02-12-2021 12:12:47 PM
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ReporteriaClaro.Clients.ApiPowerBi.Repositories.Interfaces;

namespace ReporteriaClaro.Clients.ApiPowerBi.Repositories
{
    public partial class VWEstadoLimpiezaPowerBiEntityRepository
    {
    }
}
