//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class ApiUserEntityDto
    {
        #region Constructors

        public ApiUserEntityDto() {
        }

        public ApiUserEntityDto(int id, string keyHash, string comments, System.DateTime createdAt, string createdBy, System.DateTime? modifiedAt, string modifiedBy, System.DateTime? deactivatedAt, string deactivatedBy, string deactivatedReason, bool active) {

          this.Id = id;
          this.KeyHash = keyHash;
          this.Comments = comments;
          this.CreatedAt = createdAt;
          this.CreatedBy = createdBy;
          this.ModifiedAt = modifiedAt;
          this.ModifiedBy = modifiedBy;
          this.DeactivatedAt = deactivatedAt;
          this.DeactivatedBy = deactivatedBy;
          this.DeactivatedReason = deactivatedReason;
          this.Active = active;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string KeyHash { get; set; }

        public string Comments { get; set; }

        public System.DateTime CreatedAt { get; set; }

        public string CreatedBy { get; set; }

        public System.DateTime? ModifiedAt { get; set; }

        public string ModifiedBy { get; set; }

        public System.DateTime? DeactivatedAt { get; set; }

        public string DeactivatedBy { get; set; }

        public string DeactivatedReason { get; set; }

        public bool Active { get; set; }

        #endregion
    }

}
