//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class DespachoDetalleEntityDto
    {
        #region Constructors

        public DespachoDetalleEntityDto() {
        }

        public DespachoDetalleEntityDto(int id, int equipoId, int encabezadoId, int caja, int pallet, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, System.DateTime? fechaModificacionRegistro, string usuarioModificacionRegistro, System.DateTime? fechaEliminacionRegistro, string usuarioEliminacionRegistro, bool activo, DespachoEncabezadoEntityDto despachoEncabezadoEntity, EquipoEntityDto equipoEntity) {

          this.Id = id;
          this.EquipoId = equipoId;
          this.EncabezadoId = encabezadoId;
          this.Caja = caja;
          this.Pallet = pallet;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.FechaModificacionRegistro = fechaModificacionRegistro;
          this.UsuarioModificacionRegistro = usuarioModificacionRegistro;
          this.FechaEliminacionRegistro = fechaEliminacionRegistro;
          this.UsuarioEliminacionRegistro = usuarioEliminacionRegistro;
          this.Activo = activo;
          this.DespachoEncabezadoEntity = despachoEncabezadoEntity;
          this.EquipoEntity = equipoEntity;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public int EquipoId { get; set; }

        public int EncabezadoId { get; set; }

        public int Caja { get; set; }

        public int Pallet { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public System.DateTime? FechaModificacionRegistro { get; set; }

        public string UsuarioModificacionRegistro { get; set; }

        public System.DateTime? FechaEliminacionRegistro { get; set; }

        public string UsuarioEliminacionRegistro { get; set; }

        public bool Activo { get; set; }

        #endregion

        #region Navigation Properties

        public DespachoEncabezadoEntityDto DespachoEncabezadoEntity { get; set; }

        public EquipoEntityDto EquipoEntity { get; set; }

        #endregion
    }

}
