//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class EquipoMovimientoEntityDto
    {
        #region Constructors

        public EquipoMovimientoEntityDto() {
        }

        public EquipoMovimientoEntityDto(int id, System.DateTime fecha, int equipoId, int etapaOrigenId, int etapaDestinoId, int operarioId, int? operarioDevolucionId, string observacion, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, System.DateTime? fechaModificacionRegistro, string usuarioModificacionRegistro, System.DateTime? fechaEliminacionRegistro, string usuarioEliminacionRegistro, bool activo, EtapaEntityDto etapaEntity_EtapaOrigenId, EtapaEntityDto etapaEntity_EtapaDestinoId, EquipoEntityDto equipoEntity, OperarioEntityDto operarioEntity_OperarioId, OperarioEntityDto operarioEntity_OperarioDevolucionId) {

          this.Id = id;
          this.Fecha = fecha;
          this.EquipoId = equipoId;
          this.EtapaOrigenId = etapaOrigenId;
          this.EtapaDestinoId = etapaDestinoId;
          this.OperarioId = operarioId;
          this.OperarioDevolucionId = operarioDevolucionId;
          this.Observacion = observacion;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.FechaModificacionRegistro = fechaModificacionRegistro;
          this.UsuarioModificacionRegistro = usuarioModificacionRegistro;
          this.FechaEliminacionRegistro = fechaEliminacionRegistro;
          this.UsuarioEliminacionRegistro = usuarioEliminacionRegistro;
          this.Activo = activo;
          this.EtapaEntity_EtapaOrigenId = etapaEntity_EtapaOrigenId;
          this.EtapaEntity_EtapaDestinoId = etapaEntity_EtapaDestinoId;
          this.EquipoEntity = equipoEntity;
          this.OperarioEntity_OperarioId = operarioEntity_OperarioId;
          this.OperarioEntity_OperarioDevolucionId = operarioEntity_OperarioDevolucionId;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public System.DateTime Fecha { get; set; }

        public int EquipoId { get; set; }

        public int EtapaOrigenId { get; set; }

        public int EtapaDestinoId { get; set; }

        public int OperarioId { get; set; }

        public int? OperarioDevolucionId { get; set; }

        public string Observacion { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public System.DateTime? FechaModificacionRegistro { get; set; }

        public string UsuarioModificacionRegistro { get; set; }

        public System.DateTime? FechaEliminacionRegistro { get; set; }

        public string UsuarioEliminacionRegistro { get; set; }

        public bool Activo { get; set; }

        #endregion

        #region Navigation Properties

        public EtapaEntityDto EtapaEntity_EtapaOrigenId { get; set; }

        public EtapaEntityDto EtapaEntity_EtapaDestinoId { get; set; }

        public EquipoEntityDto EquipoEntity { get; set; }

        public OperarioEntityDto OperarioEntity_OperarioId { get; set; }

        public OperarioEntityDto OperarioEntity_OperarioDevolucionId { get; set; }

        #endregion
    }

}
