//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class EtapaEntityDto
    {
        #region Constructors

        public EtapaEntityDto() {
        }

        public EtapaEntityDto(int id, string nombre, int posicion, int zonaId, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, System.DateTime? fechaModificacionRegistro, string usuarioModificacionRegistro, System.DateTime? fechaEliminacionRegistro, string usuarioEliminacionRegistro, bool activo, List<EquipoMovimientoEntityDto> equipoMovimientoEntities_EtapaOrigenId, List<EquipoMovimientoEntityDto> equipoMovimientoEntities_EtapaDestinoId, ZonaEntityDto zonaEntity, List<EtapaSecuenciaEntityDto> etapaSecuenciaEntities_EtapaId, List<EtapaSecuenciaEntityDto> etapaSecuenciaEntities_EtapaAnteriorPosteriorId) {

          this.Id = id;
          this.Nombre = nombre;
          this.Posicion = posicion;
          this.ZonaId = zonaId;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.FechaModificacionRegistro = fechaModificacionRegistro;
          this.UsuarioModificacionRegistro = usuarioModificacionRegistro;
          this.FechaEliminacionRegistro = fechaEliminacionRegistro;
          this.UsuarioEliminacionRegistro = usuarioEliminacionRegistro;
          this.Activo = activo;
          this.EquipoMovimientoEntities_EtapaOrigenId = equipoMovimientoEntities_EtapaOrigenId;
          this.EquipoMovimientoEntities_EtapaDestinoId = equipoMovimientoEntities_EtapaDestinoId;
          this.ZonaEntity = zonaEntity;
          this.EtapaSecuenciaEntities_EtapaId = etapaSecuenciaEntities_EtapaId;
          this.EtapaSecuenciaEntities_EtapaAnteriorPosteriorId = etapaSecuenciaEntities_EtapaAnteriorPosteriorId;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Nombre { get; set; }

        public int Posicion { get; set; }

        public int ZonaId { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public System.DateTime? FechaModificacionRegistro { get; set; }

        public string UsuarioModificacionRegistro { get; set; }

        public System.DateTime? FechaEliminacionRegistro { get; set; }

        public string UsuarioEliminacionRegistro { get; set; }

        public bool Activo { get; set; }

        #endregion

        #region Navigation Properties

        public List<EquipoMovimientoEntityDto> EquipoMovimientoEntities_EtapaOrigenId { get; set; }

        public List<EquipoMovimientoEntityDto> EquipoMovimientoEntities_EtapaDestinoId { get; set; }

        public ZonaEntityDto ZonaEntity { get; set; }

        public List<EtapaSecuenciaEntityDto> EtapaSecuenciaEntities_EtapaId { get; set; }

        public List<EtapaSecuenciaEntityDto> EtapaSecuenciaEntities_EtapaAnteriorPosteriorId { get; set; }

        #endregion
    }

}
