//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class IdentityUserExceptionLogEntityDto
    {
        #region Constructors

        public IdentityUserExceptionLogEntityDto() {
        }

        public IdentityUserExceptionLogEntityDto(int id, string userId, string message, string type, string source, string url, System.DateTime createdAt, IdentityUserEntityDto identityUserEntity) {

          this.Id = id;
          this.UserId = userId;
          this.Message = message;
          this.Type = type;
          this.Source = source;
          this.Url = url;
          this.CreatedAt = createdAt;
          this.IdentityUserEntity = identityUserEntity;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string UserId { get; set; }

        public string Message { get; set; }

        public string Type { get; set; }

        public string Source { get; set; }

        public string Url { get; set; }

        public System.DateTime CreatedAt { get; set; }

        #endregion

        #region Navigation Properties

        public IdentityUserEntityDto IdentityUserEntity { get; set; }

        #endregion
    }

}
