//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class SPSeguimientoUltimoMovimientoEntityResultDto
    {
        #region Constructors

        public SPSeguimientoUltimoMovimientoEntityResultDto() {
        }

        public SPSeguimientoUltimoMovimientoEntityResultDto(int id, System.DateTime fecha, string esn, string origen, string destino, string operario, string operarioDevolucion, string observacion) {

          this.Id = id;
          this.Fecha = fecha;
          this.Esn = esn;
          this.Origen = origen;
          this.Destino = destino;
          this.Operario = operario;
          this.OperarioDevolucion = operarioDevolucion;
          this.Observacion = observacion;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public System.DateTime Fecha { get; set; }

        public string Esn { get; set; }

        public string Origen { get; set; }

        public string Destino { get; set; }

        public string Operario { get; set; }

        public string OperarioDevolucion { get; set; }

        public string Observacion { get; set; }

        #endregion
    }

}
