//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class SPUltimoOperarioEtapaEntityResultDto
    {
        #region Constructors

        public SPUltimoOperarioEtapaEntityResultDto() {
        }

        public SPUltimoOperarioEtapaEntityResultDto(int id, string nombre) {

          this.Id = id;
          this.Nombre = nombre;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Nombre { get; set; }

        #endregion
    }

}
