//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public partial class TempDespachoCsvEntityDto
    {
        #region Constructors

        public TempDespachoCsvEntityDto() {
        }

        public TempDespachoCsvEntityDto(int id, string esn, System.DateTime fecha, string guia, string estadoDespacho, string operario, int caja, int pallet, string estadoFuentePoder, string estadoUtp, string estadoControlRemoto, string estadoHdmi, string estadoRca, bool pintura, string derivada, bool procesoFinalizado, int? equipoId, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, bool cargaExitosa) {

          this.Id = id;
          this.Esn = esn;
          this.Fecha = fecha;
          this.Guia = guia;
          this.EstadoDespacho = estadoDespacho;
          this.Operario = operario;
          this.Caja = caja;
          this.Pallet = pallet;
          this.EstadoFuentePoder = estadoFuentePoder;
          this.EstadoUtp = estadoUtp;
          this.EstadoControlRemoto = estadoControlRemoto;
          this.EstadoHdmi = estadoHdmi;
          this.EstadoRca = estadoRca;
          this.Pintura = pintura;
          this.Derivada = derivada;
          this.ProcesoFinalizado = procesoFinalizado;
          this.EquipoId = equipoId;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.CargaExitosa = cargaExitosa;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Esn { get; set; }

        public System.DateTime Fecha { get; set; }

        public string Guia { get; set; }

        public string EstadoDespacho { get; set; }

        public string Operario { get; set; }

        public int Caja { get; set; }

        public int Pallet { get; set; }

        public string EstadoFuentePoder { get; set; }

        public string EstadoUtp { get; set; }

        public string EstadoControlRemoto { get; set; }

        public string EstadoHdmi { get; set; }

        public string EstadoRca { get; set; }

        public bool Pintura { get; set; }

        public string Derivada { get; set; }

        public bool ProcesoFinalizado { get; set; }

        public int? EquipoId { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public bool CargaExitosa { get; set; }

        #endregion
    }

}
