//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 10-11-2021 01:36:07 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaMovistar.Domain.Models.Entities;
using ReporteriaMovistar.Domain.Models.Pagination;
using ReporteriaMovistar.Domain.Models.Sorting;

namespace ReporteriaMovistar.Domain.Interfaces.Repositories
{
    public partial interface IDespachoEncabezadoEntityRepository
    {
	    public Task BulkInsertConDetalleAsync(IList<DespachoEncabezadoEntity> entities);

	    public Task<bool> ExisteEncabezadoAsync(string guia);

        public Task<DespachoEncabezadoEntity> FindAsync(int id);

	    public Task<PagedResult<DespachoEncabezadoEntity>> GetPaginadoAsync(string guiaBuscada, bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
