//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 08-11-2021 12:59:49 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaMovistar.Domain.Models.Entities;
using ReporteriaMovistar.Domain.Models.Pagination;
using ReporteriaMovistar.Domain.Models.Sorting;

namespace ReporteriaMovistar.Domain.Interfaces.Repositories
{
    public partial interface IEquipoEntityRepository
    {
	    public Task<IEnumerable<EquipoEntity>> GetTop20Async(string esnBuscado);

        public Task<PagedResult<EquipoEntity>> GetPaginadoAsync(string esnBuscado, bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
