//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02-11-2021 02:48:11 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaMovistar.Domain.Models.Entities;
using ReporteriaMovistar.Domain.Models.Pagination;
using ReporteriaMovistar.Domain.Models.Sorting;

namespace ReporteriaMovistar.Domain.Interfaces.Repositories
{
    public partial interface IEtapaEstadoEntityRepository
    {
	    public Task<bool> ExistePosicionAsync(int position);

	    public Task BatchUpdatePosicionAsync(int position);

	    public Task<EtapaEstadoEntity> FindAsync(int id);

	    public Task<IEnumerable<EtapaEstadoEntity>> GetAsync();

	    public Task<PagedResult<EtapaEstadoEntity>> GetPaginadoAsync(bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
