//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 22-11-2021 11:44:14 AM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ReporteriaMovistar.Domain.Interfaces.Repositories
{
    public partial interface ITempDespachoCsvEntityRepository
    {
	    public Task BatchDeleteCargaNoExitosaAsync();
    }
}
