//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 16-11-2021 10:13:03 AM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaMovistar.Domain.Models.Entities;
using ReporteriaMovistar.Domain.Models.Pagination;
using ReporteriaMovistar.Domain.Models.Sorting;

namespace ReporteriaMovistar.Domain.Interfaces.Repositories
{
    public partial interface IVWMovimientoEquipoEntityRepository
    {
	    public Task<IEnumerable<VWMovimientoEquipoEntity>> GetByEsnPaginadoAsync(string esnBuscado, bool activeRecords);

        public Task<PagedResult<VWMovimientoEquipoEntity>> GetByEtapaOrigenPaginadoAsync(string esnBuscado, int idEtapaOrigen, bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);

        public Task<PagedResult<VWMovimientoEquipoEntity>> GetByEtapaDestinoPaginadoAsync(string esnBuscado, int idEtapaDestino, bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
