//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public static partial class EFMigrationsHistoryEntityConverter
    {

        public static EFMigrationsHistoryEntityDto ToDto(this ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static EFMigrationsHistoryEntityDto ToDtoWithRelated(this ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new EFMigrationsHistoryEntityDto();

            // Properties
            target.MigrationId = source.MigrationId;
            target.ProductVersion = source.ProductVersion;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity ToEntity(this EFMigrationsHistoryEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity();

            // Properties
            target.MigrationId = source.MigrationId;
            target.ProductVersion = source.ProductVersion;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<EFMigrationsHistoryEntityDto> ToDtos(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<EFMigrationsHistoryEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity> ToEntities(this IEnumerable<EFMigrationsHistoryEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity source, EFMigrationsHistoryEntityDto target);

        static partial void OnEntityCreating(EFMigrationsHistoryEntityDto source, ReporteriaClaro.Domain.Models.Entities.EFMigrationsHistoryEntity target);

    }

}
