//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public static partial class EquipoMarcaEntityConverter
    {

        public static EquipoMarcaEntityDto ToDto(this ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static EquipoMarcaEntityDto ToDtoWithRelated(this ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new EquipoMarcaEntityDto();

            // Properties
            target.Id = source.Id;
            target.Nombre = source.Nombre;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // Navigation Properties
            if (level > 0) {
              target.EquipoModeloEntities = source.EquipoModeloEntities.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity ToEntity(this EquipoMarcaEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity();

            // Properties
            target.Id = source.Id;
            target.Nombre = source.Nombre;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<EquipoMarcaEntityDto> ToDtos(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<EquipoMarcaEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity> ToEntities(this IEnumerable<EquipoMarcaEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity source, EquipoMarcaEntityDto target);

        static partial void OnEntityCreating(EquipoMarcaEntityDto source, ReporteriaClaro.Domain.Models.Entities.EquipoMarcaEntity target);

    }

}
