//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public static partial class EquipoMovimientoEntityConverter
    {

        public static EquipoMovimientoEntityDto ToDto(this ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static EquipoMovimientoEntityDto ToDtoWithRelated(this ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new EquipoMovimientoEntityDto();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.EquipoId = source.EquipoId;
            target.EtapaOrigenId = source.EtapaOrigenId;
            target.EtapaDestinoId = source.EtapaDestinoId;
            target.OperarioId = source.OperarioId;
            target.OperarioDevolucionId = source.OperarioDevolucionId;
            target.Observacion = source.Observacion;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // Navigation Properties
            if (level > 0) {
              target.EtapaEntity_EtapaOrigenId = source.EtapaEntity_EtapaOrigenId.ToDtoWithRelated(level - 1);
              target.EtapaEntity_EtapaDestinoId = source.EtapaEntity_EtapaDestinoId.ToDtoWithRelated(level - 1);
              target.EquipoEntity = source.EquipoEntity.ToDtoWithRelated(level - 1);
              target.OperarioEntity_OperarioId = source.OperarioEntity_OperarioId.ToDtoWithRelated(level - 1);
              target.OperarioEntity_OperarioDevolucionId = source.OperarioEntity_OperarioDevolucionId.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity ToEntity(this EquipoMovimientoEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity();

            // Properties
            target.Id = source.Id;
            target.Fecha = source.Fecha;
            target.EquipoId = source.EquipoId;
            target.EtapaOrigenId = source.EtapaOrigenId;
            target.EtapaDestinoId = source.EtapaDestinoId;
            target.OperarioId = source.OperarioId;
            target.OperarioDevolucionId = source.OperarioDevolucionId;
            target.Observacion = source.Observacion;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<EquipoMovimientoEntityDto> ToDtos(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<EquipoMovimientoEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity> ToEntities(this IEnumerable<EquipoMovimientoEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity source, EquipoMovimientoEntityDto target);

        static partial void OnEntityCreating(EquipoMovimientoEntityDto source, ReporteriaClaro.Domain.Models.Entities.EquipoMovimientoEntity target);

    }

}
