//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ReporteriaClaro.Application.Models.Transfer
{

    public static partial class EtapaSecuenciaEntityConverter
    {

        public static EtapaSecuenciaEntityDto ToDto(this ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static EtapaSecuenciaEntityDto ToDtoWithRelated(this ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity source, int level)
        {
            if (source == null)
              return null;

            var target = new EtapaSecuenciaEntityDto();

            // Properties
            target.Id = source.Id;
            target.EtapaId = source.EtapaId;
            target.EtapaAnteriorPosteriorId = source.EtapaAnteriorPosteriorId;
            target.EsEtapaAnterior = source.EsEtapaAnterior;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // Navigation Properties
            if (level > 0) {
              target.EtapaEntity_EtapaId = source.EtapaEntity_EtapaId.ToDtoWithRelated(level - 1);
              target.EtapaEntity_EtapaAnteriorPosteriorId = source.EtapaEntity_EtapaAnteriorPosteriorId.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity ToEntity(this EtapaSecuenciaEntityDto source)
        {
            if (source == null)
              return null;

            var target = new ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity();

            // Properties
            target.Id = source.Id;
            target.EtapaId = source.EtapaId;
            target.EtapaAnteriorPosteriorId = source.EtapaAnteriorPosteriorId;
            target.EsEtapaAnterior = source.EsEtapaAnterior;
            target.FechaCreacionRegistro = source.FechaCreacionRegistro;
            target.UsuarioCreacionRegistro = source.UsuarioCreacionRegistro;
            target.FechaModificacionRegistro = source.FechaModificacionRegistro;
            target.UsuarioModificacionRegistro = source.UsuarioModificacionRegistro;
            target.FechaEliminacionRegistro = source.FechaEliminacionRegistro;
            target.UsuarioEliminacionRegistro = source.UsuarioEliminacionRegistro;
            target.Activo = source.Activo;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<EtapaSecuenciaEntityDto> ToDtos(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<EtapaSecuenciaEntityDto> ToDtosWithRelated(this IEnumerable<ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity> ToEntities(this IEnumerable<EtapaSecuenciaEntityDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity source, EtapaSecuenciaEntityDto target);

        static partial void OnEntityCreating(EtapaSecuenciaEntityDto source, ReporteriaClaro.Domain.Models.Entities.EtapaSecuenciaEntity target);

    }

}
