//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public partial class EquipoModeloEntityDto
    {
        #region Constructors

        public EquipoModeloEntityDto() {
        }

        public EquipoModeloEntityDto(int id, string nombre, int marcaId, int? tecnologiaId, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, System.DateTime? fechaModificacionRegistro, string usuarioModificacionRegistro, System.DateTime? fechaEliminacionRegistro, string usuarioEliminacionRegistro, bool activo, EquipoMarcaEntityDto equipoMarcaEntity, EquipoTecnologiaEntityDto equipoTecnologiaEntity, List<EquipoEntityDto> equipoEntities) {

          this.Id = id;
          this.Nombre = nombre;
          this.MarcaId = marcaId;
          this.TecnologiaId = tecnologiaId;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.FechaModificacionRegistro = fechaModificacionRegistro;
          this.UsuarioModificacionRegistro = usuarioModificacionRegistro;
          this.FechaEliminacionRegistro = fechaEliminacionRegistro;
          this.UsuarioEliminacionRegistro = usuarioEliminacionRegistro;
          this.Activo = activo;
          this.EquipoMarcaEntity = equipoMarcaEntity;
          this.EquipoTecnologiaEntity = equipoTecnologiaEntity;
          this.EquipoEntities = equipoEntities;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Nombre { get; set; }

        public int MarcaId { get; set; }

        public int? TecnologiaId { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public System.DateTime? FechaModificacionRegistro { get; set; }

        public string UsuarioModificacionRegistro { get; set; }

        public System.DateTime? FechaEliminacionRegistro { get; set; }

        public string UsuarioEliminacionRegistro { get; set; }

        public bool Activo { get; set; }

        #endregion

        #region Navigation Properties

        public EquipoMarcaEntityDto EquipoMarcaEntity { get; set; }

        public EquipoTecnologiaEntityDto EquipoTecnologiaEntity { get; set; }

        public List<EquipoEntityDto> EquipoEntities { get; set; }

        #endregion
    }

}
