//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public partial class EquipoEntityDto
    {
        #region Constructors

        public EquipoEntityDto() {
        }

        public EquipoEntityDto(int id, decimal headerId, System.DateTime fecha, string esn, string numeroReferencia, int? modeloId, int? colorId, string tipo, string subtipo, string categoria, string subcategoria, string estado, string subestado, int? fuentePoderEstadoId, int? utpEstadoId, int? controlRemotoEstadoId, int? hdmiEstadoId, int? rcaEstadoId, bool pintura, string derivada, bool procesoFinalizado, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, System.DateTime? fechaModificacionRegistro, string usuarioModificacionRegistro, System.DateTime? fechaEliminacionRegistro, string usuarioEliminacionRegistro, bool activo, EquipoColorEntityDto equipoColorEntity, EquipoModeloEntityDto equipoModeloEntity, List<EquipoMovimientoEntityDto> equipoMovimientoEntities, List<DespachoDetalleEntityDto> despachoDetalleEntities, List<EquipoScrapEntityDto> equipoScrapEntities, ComponenteEstadoEntityDto componenteEstadoEntity_FuentePoderEstadoId, ComponenteEstadoEntityDto componenteEstadoEntity_UtpEstadoId, ComponenteEstadoEntityDto componenteEstadoEntity_ControlRemotoEstadoId, ComponenteEstadoEntityDto componenteEstadoEntity_HdmiEstadoId, ComponenteEstadoEntityDto componenteEstadoEntity_RcaEstadoId) {

          this.Id = id;
          this.HeaderId = headerId;
          this.Fecha = fecha;
          this.Esn = esn;
          this.NumeroReferencia = numeroReferencia;
          this.ModeloId = modeloId;
          this.ColorId = colorId;
          this.Tipo = tipo;
          this.Subtipo = subtipo;
          this.Categoria = categoria;
          this.Subcategoria = subcategoria;
          this.Estado = estado;
          this.Subestado = subestado;
          this.FuentePoderEstadoId = fuentePoderEstadoId;
          this.UtpEstadoId = utpEstadoId;
          this.ControlRemotoEstadoId = controlRemotoEstadoId;
          this.HdmiEstadoId = hdmiEstadoId;
          this.RcaEstadoId = rcaEstadoId;
          this.Pintura = pintura;
          this.Derivada = derivada;
          this.ProcesoFinalizado = procesoFinalizado;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.FechaModificacionRegistro = fechaModificacionRegistro;
          this.UsuarioModificacionRegistro = usuarioModificacionRegistro;
          this.FechaEliminacionRegistro = fechaEliminacionRegistro;
          this.UsuarioEliminacionRegistro = usuarioEliminacionRegistro;
          this.Activo = activo;
          this.EquipoColorEntity = equipoColorEntity;
          this.EquipoModeloEntity = equipoModeloEntity;
          this.EquipoMovimientoEntities = equipoMovimientoEntities;
          this.DespachoDetalleEntities = despachoDetalleEntities;
          this.EquipoScrapEntities = equipoScrapEntities;
          this.ComponenteEstadoEntity_FuentePoderEstadoId = componenteEstadoEntity_FuentePoderEstadoId;
          this.ComponenteEstadoEntity_UtpEstadoId = componenteEstadoEntity_UtpEstadoId;
          this.ComponenteEstadoEntity_ControlRemotoEstadoId = componenteEstadoEntity_ControlRemotoEstadoId;
          this.ComponenteEstadoEntity_HdmiEstadoId = componenteEstadoEntity_HdmiEstadoId;
          this.ComponenteEstadoEntity_RcaEstadoId = componenteEstadoEntity_RcaEstadoId;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public decimal HeaderId { get; set; }

        public System.DateTime Fecha { get; set; }

        public string Esn { get; set; }

        public string NumeroReferencia { get; set; }

        public int? ModeloId { get; set; }

        public int? ColorId { get; set; }

        public string Tipo { get; set; }

        public string Subtipo { get; set; }

        public string Categoria { get; set; }

        public string Subcategoria { get; set; }

        public string Estado { get; set; }

        public string Subestado { get; set; }

        public int? FuentePoderEstadoId { get; set; }

        public int? UtpEstadoId { get; set; }

        public int? ControlRemotoEstadoId { get; set; }

        public int? HdmiEstadoId { get; set; }

        public int? RcaEstadoId { get; set; }

        public bool Pintura { get; set; }

        public string Derivada { get; set; }

        public bool ProcesoFinalizado { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public System.DateTime? FechaModificacionRegistro { get; set; }

        public string UsuarioModificacionRegistro { get; set; }

        public System.DateTime? FechaEliminacionRegistro { get; set; }

        public string UsuarioEliminacionRegistro { get; set; }

        public bool Activo { get; set; }

        #endregion

        #region Navigation Properties

        public EquipoColorEntityDto EquipoColorEntity { get; set; }

        public EquipoModeloEntityDto EquipoModeloEntity { get; set; }

        public List<EquipoMovimientoEntityDto> EquipoMovimientoEntities { get; set; }

        public List<DespachoDetalleEntityDto> DespachoDetalleEntities { get; set; }

        public List<EquipoScrapEntityDto> EquipoScrapEntities { get; set; }

        public ComponenteEstadoEntityDto ComponenteEstadoEntity_FuentePoderEstadoId { get; set; }

        public ComponenteEstadoEntityDto ComponenteEstadoEntity_UtpEstadoId { get; set; }

        public ComponenteEstadoEntityDto ComponenteEstadoEntity_ControlRemotoEstadoId { get; set; }

        public ComponenteEstadoEntityDto ComponenteEstadoEntity_HdmiEstadoId { get; set; }

        public ComponenteEstadoEntityDto ComponenteEstadoEntity_RcaEstadoId { get; set; }

        #endregion
    }

}
