//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public partial class IdentityRoleEntityDto
    {
        #region Constructors

        public IdentityRoleEntityDto() {
        }

        public IdentityRoleEntityDto(string id, bool availableAsAdmin, bool availableAsSuperAdmin, System.DateTime createdAt, string createdBy, System.DateTime? modifiedAt, string modifiedBy, System.DateTime? deactivatedAt, string deactivatedBy, string name, string normalizedName, string concurrencyStamp, List<IdentityRoleClaimEntityDto> identityRoleClaimEntities, List<IdentityUserRoleEntityDto> identityUserRoleEntities) {

          this.Id = id;
          this.AvailableAsAdmin = availableAsAdmin;
          this.AvailableAsSuperAdmin = availableAsSuperAdmin;
          this.CreatedAt = createdAt;
          this.CreatedBy = createdBy;
          this.ModifiedAt = modifiedAt;
          this.ModifiedBy = modifiedBy;
          this.DeactivatedAt = deactivatedAt;
          this.DeactivatedBy = deactivatedBy;
          this.Name = name;
          this.NormalizedName = normalizedName;
          this.ConcurrencyStamp = concurrencyStamp;
          this.IdentityRoleClaimEntities = identityRoleClaimEntities;
          this.IdentityUserRoleEntities = identityUserRoleEntities;
        }

        #endregion

        #region Properties

        public string Id { get; set; }

        public bool AvailableAsAdmin { get; set; }

        public bool AvailableAsSuperAdmin { get; set; }

        public System.DateTime CreatedAt { get; set; }

        public string CreatedBy { get; set; }

        public System.DateTime? ModifiedAt { get; set; }

        public string ModifiedBy { get; set; }

        public System.DateTime? DeactivatedAt { get; set; }

        public string DeactivatedBy { get; set; }

        public string Name { get; set; }

        public string NormalizedName { get; set; }

        public string ConcurrencyStamp { get; set; }

        #endregion

        #region Navigation Properties

        public List<IdentityRoleClaimEntityDto> IdentityRoleClaimEntities { get; set; }

        public List<IdentityUserRoleEntityDto> IdentityUserRoleEntities { get; set; }

        #endregion
    }

}
