//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public partial class SPInformacionEquipoEntityResultDto
    {
        #region Constructors

        public SPInformacionEquipoEntityResultDto() {
        }

        public SPInformacionEquipoEntityResultDto(int id, string esn, string marca, string modelo, string color, int? tecnologiaId, string tecnologia) {

          this.Id = id;
          this.Esn = esn;
          this.Marca = marca;
          this.Modelo = modelo;
          this.Color = color;
          this.TecnologiaId = tecnologiaId;
          this.Tecnologia = tecnologia;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Esn { get; set; }

        public string Marca { get; set; }

        public string Modelo { get; set; }

        public string Color { get; set; }

        public int? TecnologiaId { get; set; }

        public string Tecnologia { get; set; }

        #endregion
    }

}
