//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public partial class SPSeguimientoEquipoEntityResultDto
    {
        #region Constructors

        public SPSeguimientoEquipoEntityResultDto() {
        }

        public SPSeguimientoEquipoEntityResultDto(int id, System.DateTime fechaRecepcion, string esn, string marca, string modelo, string color, string tecnologia, string configuracion, string detalleConfiguracion) {

          this.Id = id;
          this.FechaRecepcion = fechaRecepcion;
          this.Esn = esn;
          this.Marca = marca;
          this.Modelo = modelo;
          this.Color = color;
          this.Tecnologia = tecnologia;
          this.Configuracion = configuracion;
          this.DetalleConfiguracion = detalleConfiguracion;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public System.DateTime FechaRecepcion { get; set; }

        public string Esn { get; set; }

        public string Marca { get; set; }

        public string Modelo { get; set; }

        public string Color { get; set; }

        public string Tecnologia { get; set; }

        public string Configuracion { get; set; }

        public string DetalleConfiguracion { get; set; }

        #endregion
    }

}
