//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 10-12-2021 02:28:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ReporteriaMovistar.Application.Models.Transfer
{

    public partial class TempEquipoMovimientoCsvEntityDto
    {
        #region Constructors

        public TempEquipoMovimientoCsvEntityDto() {
        }

        public TempEquipoMovimientoCsvEntityDto(int id, System.DateTime fecha, string esn, string operario, string operarioDevolucion, string observacion, int? equipoId, int? operarioId, int? operarioDevolucionId, System.DateTime fechaCreacionRegistro, string usuarioCreacionRegistro, bool cargaExitosa) {

          this.Id = id;
          this.Fecha = fecha;
          this.Esn = esn;
          this.Operario = operario;
          this.OperarioDevolucion = operarioDevolucion;
          this.Observacion = observacion;
          this.EquipoId = equipoId;
          this.OperarioId = operarioId;
          this.OperarioDevolucionId = operarioDevolucionId;
          this.FechaCreacionRegistro = fechaCreacionRegistro;
          this.UsuarioCreacionRegistro = usuarioCreacionRegistro;
          this.CargaExitosa = cargaExitosa;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public System.DateTime Fecha { get; set; }

        public string Esn { get; set; }

        public string Operario { get; set; }

        public string OperarioDevolucion { get; set; }

        public string Observacion { get; set; }

        public int? EquipoId { get; set; }

        public int? OperarioId { get; set; }

        public int? OperarioDevolucionId { get; set; }

        public System.DateTime FechaCreacionRegistro { get; set; }

        public string UsuarioCreacionRegistro { get; set; }

        public bool CargaExitosa { get; set; }

        #endregion
    }

}
