//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 10-12-2021 02:28:28 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using ReporteriaClaro.Domain.Interfaces.Repositories;

namespace ReporteriaClaro.Infrastructure.Data.Repositories
{
    public partial class IdentityUserLoginEntityRepository : EntityFrameworkRepository<ReporteriaClaro.Domain.Models.Entities.IdentityUserLoginEntity>, IIdentityUserLoginEntityRepository
    {
        public IdentityUserLoginEntityRepository(ReporteriaClaro.Infrastructure.Data.DataProviders.ReporteriaClaroDbContext context)
            : base(context)
        {
        }

        public virtual ICollection<ReporteriaClaro.Domain.Models.Entities.IdentityUserLoginEntity> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual ReporteriaClaro.Domain.Models.Entities.IdentityUserLoginEntity GetByKey(string _LoginProvider, string _ProviderKey)
        {
            return objectSet.SingleOrDefault(e => e.LoginProvider == _LoginProvider && e.ProviderKey == _ProviderKey);
        }

        public new ReporteriaClaro.Infrastructure.Data.DataProviders.ReporteriaClaroDbContext Context 
        {
            get
            {
                return (ReporteriaClaro.Infrastructure.Data.DataProviders.ReporteriaClaroDbContext)base.Context;
            }
        }
    }
}
