//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 10-12-2021 02:28:28 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ReporteriaMovistar.Domain.Interfaces.Repositories;
using ReporteriaMovistar.Infrastructure.Data.DataProviders;

namespace ReporteriaMovistar.Infrastructure.Data.Repositories
{
    public partial class EntityFrameworkUnitOfWork : IUnitOfWork
    {
        protected DbContext context = null;

        IIdentityRoleEntityRepository _IdentityRoleEntities;

        IIdentityRoleClaimEntityRepository _IdentityRoleClaimEntities;

        IIdentityUserEntityRepository _IdentityUserEntities;

        IIdentityUserAccessLogEntityRepository _IdentityUserAccessLogEntities;

        IIdentityUserClaimEntityRepository _IdentityUserClaimEntities;

        IIdentityUserExceptionLogEntityRepository _IdentityUserExceptionLogEntities;

        IIdentityUserLoginEntityRepository _IdentityUserLoginEntities;

        IIdentityUserOperationLogEntityRepository _IdentityUserOperationLogEntities;

        IIdentityUserRoleEntityRepository _IdentityUserRoleEntities;

        IIdentityUserTokenEntityRepository _IdentityUserTokenEntities;

        IEFMigrationsHistoryEntityRepository _EFMigrationsHistoryEntities;

        IEquipoColorEntityRepository _EquipoColorEntities;

        IEquipoMarcaEntityRepository _EquipoMarcaEntities;

        IEquipoModeloEntityRepository _EquipoModeloEntities;

        IEquipoMovimientoEntityRepository _EquipoMovimientoEntities;

        IEtapaEntityRepository _EtapaEntities;

        IComponenteEstadoEntityRepository _ComponenteEstadoEntities;

        IDespachoEstadoEntityRepository _DespachoEstadoEntities;

        IEtapaEstadoEntityRepository _EtapaEstadoEntities;

        IPronosticoEntityRepository _PronosticoEntities;

        IZonaEntityRepository _ZonaEntities;

        IEquipoTecnologiaEntityRepository _EquipoTecnologiaEntities;

        IEquipoConfiguracionEntityRepository _EquipoConfiguracionEntities;

        IEquipoEntityRepository _EquipoEntities;

        IDespachoDetalleEntityRepository _DespachoDetalleEntities;

        IDespachoEncabezadoEntityRepository _DespachoEncabezadoEntities;

        IEquipoScrapEntityRepository _EquipoScrapEntities;

        IVWMovimientoEquipoEntityRepository _VWMovimientoEquipoEntities;

        IOperarioEntityRepository _OperarioEntities;

        ITempDespachoCsvEntityRepository _TempDespachoCsvEntities;

        IApiUserEntityRepository _ApiUserEntities;

        IEtapaSecuenciaEntityRepository _EtapaSecuenciaEntities;

        ITempEquipoMovimientoCsvEntityRepository _TempEquipoMovimientoCsvEntities;

        public EntityFrameworkUnitOfWork(DbContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }
            this.context = context;
        }

        public DbContext Context
        {
            get
            {
                return context;
            }
        }

        protected virtual void CloseContext()
        {
            if (context != null)
            {
                context.Dispose();
                context = null;
            }
        }

        #region IDisposable Methods

        private bool disposed = false;

        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    CloseContext();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

        #region IUnitOfWork Members

        public IIdentityRoleEntityRepository IdentityRoleEntities {
          get {
            if (_IdentityRoleEntities == null)
              _IdentityRoleEntities = new IdentityRoleEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityRoleEntities;
          }
        }

        public IIdentityRoleClaimEntityRepository IdentityRoleClaimEntities {
          get {
            if (_IdentityRoleClaimEntities == null)
              _IdentityRoleClaimEntities = new IdentityRoleClaimEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityRoleClaimEntities;
          }
        }

        public IIdentityUserEntityRepository IdentityUserEntities {
          get {
            if (_IdentityUserEntities == null)
              _IdentityUserEntities = new IdentityUserEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserEntities;
          }
        }

        public IIdentityUserAccessLogEntityRepository IdentityUserAccessLogEntities {
          get {
            if (_IdentityUserAccessLogEntities == null)
              _IdentityUserAccessLogEntities = new IdentityUserAccessLogEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserAccessLogEntities;
          }
        }

        public IIdentityUserClaimEntityRepository IdentityUserClaimEntities {
          get {
            if (_IdentityUserClaimEntities == null)
              _IdentityUserClaimEntities = new IdentityUserClaimEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserClaimEntities;
          }
        }

        public IIdentityUserExceptionLogEntityRepository IdentityUserExceptionLogEntities {
          get {
            if (_IdentityUserExceptionLogEntities == null)
              _IdentityUserExceptionLogEntities = new IdentityUserExceptionLogEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserExceptionLogEntities;
          }
        }

        public IIdentityUserLoginEntityRepository IdentityUserLoginEntities {
          get {
            if (_IdentityUserLoginEntities == null)
              _IdentityUserLoginEntities = new IdentityUserLoginEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserLoginEntities;
          }
        }

        public IIdentityUserOperationLogEntityRepository IdentityUserOperationLogEntities {
          get {
            if (_IdentityUserOperationLogEntities == null)
              _IdentityUserOperationLogEntities = new IdentityUserOperationLogEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserOperationLogEntities;
          }
        }

        public IIdentityUserRoleEntityRepository IdentityUserRoleEntities {
          get {
            if (_IdentityUserRoleEntities == null)
              _IdentityUserRoleEntities = new IdentityUserRoleEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserRoleEntities;
          }
        }

        public IIdentityUserTokenEntityRepository IdentityUserTokenEntities {
          get {
            if (_IdentityUserTokenEntities == null)
              _IdentityUserTokenEntities = new IdentityUserTokenEntityRepository((ReporteriaMovistarDbContext)context);
            return _IdentityUserTokenEntities;
          }
        }

        public IEFMigrationsHistoryEntityRepository EFMigrationsHistoryEntities {
          get {
            if (_EFMigrationsHistoryEntities == null)
              _EFMigrationsHistoryEntities = new EFMigrationsHistoryEntityRepository((ReporteriaMovistarDbContext)context);
            return _EFMigrationsHistoryEntities;
          }
        }

        public IEquipoColorEntityRepository EquipoColorEntities {
          get {
            if (_EquipoColorEntities == null)
              _EquipoColorEntities = new EquipoColorEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoColorEntities;
          }
        }

        public IEquipoMarcaEntityRepository EquipoMarcaEntities {
          get {
            if (_EquipoMarcaEntities == null)
              _EquipoMarcaEntities = new EquipoMarcaEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoMarcaEntities;
          }
        }

        public IEquipoModeloEntityRepository EquipoModeloEntities {
          get {
            if (_EquipoModeloEntities == null)
              _EquipoModeloEntities = new EquipoModeloEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoModeloEntities;
          }
        }

        public IEquipoMovimientoEntityRepository EquipoMovimientoEntities {
          get {
            if (_EquipoMovimientoEntities == null)
              _EquipoMovimientoEntities = new EquipoMovimientoEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoMovimientoEntities;
          }
        }

        public IEtapaEntityRepository EtapaEntities {
          get {
            if (_EtapaEntities == null)
              _EtapaEntities = new EtapaEntityRepository((ReporteriaMovistarDbContext)context);
            return _EtapaEntities;
          }
        }

        public IComponenteEstadoEntityRepository ComponenteEstadoEntities {
          get {
            if (_ComponenteEstadoEntities == null)
              _ComponenteEstadoEntities = new ComponenteEstadoEntityRepository((ReporteriaMovistarDbContext)context);
            return _ComponenteEstadoEntities;
          }
        }

        public IDespachoEstadoEntityRepository DespachoEstadoEntities {
          get {
            if (_DespachoEstadoEntities == null)
              _DespachoEstadoEntities = new DespachoEstadoEntityRepository((ReporteriaMovistarDbContext)context);
            return _DespachoEstadoEntities;
          }
        }

        public IEtapaEstadoEntityRepository EtapaEstadoEntities {
          get {
            if (_EtapaEstadoEntities == null)
              _EtapaEstadoEntities = new EtapaEstadoEntityRepository((ReporteriaMovistarDbContext)context);
            return _EtapaEstadoEntities;
          }
        }

        public IPronosticoEntityRepository PronosticoEntities {
          get {
            if (_PronosticoEntities == null)
              _PronosticoEntities = new PronosticoEntityRepository((ReporteriaMovistarDbContext)context);
            return _PronosticoEntities;
          }
        }

        public IZonaEntityRepository ZonaEntities {
          get {
            if (_ZonaEntities == null)
              _ZonaEntities = new ZonaEntityRepository((ReporteriaMovistarDbContext)context);
            return _ZonaEntities;
          }
        }

        public IEquipoTecnologiaEntityRepository EquipoTecnologiaEntities {
          get {
            if (_EquipoTecnologiaEntities == null)
              _EquipoTecnologiaEntities = new EquipoTecnologiaEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoTecnologiaEntities;
          }
        }

        public IEquipoConfiguracionEntityRepository EquipoConfiguracionEntities {
          get {
            if (_EquipoConfiguracionEntities == null)
              _EquipoConfiguracionEntities = new EquipoConfiguracionEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoConfiguracionEntities;
          }
        }

        public IEquipoEntityRepository EquipoEntities {
          get {
            if (_EquipoEntities == null)
              _EquipoEntities = new EquipoEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoEntities;
          }
        }

        public IDespachoDetalleEntityRepository DespachoDetalleEntities {
          get {
            if (_DespachoDetalleEntities == null)
              _DespachoDetalleEntities = new DespachoDetalleEntityRepository((ReporteriaMovistarDbContext)context);
            return _DespachoDetalleEntities;
          }
        }

        public IDespachoEncabezadoEntityRepository DespachoEncabezadoEntities {
          get {
            if (_DespachoEncabezadoEntities == null)
              _DespachoEncabezadoEntities = new DespachoEncabezadoEntityRepository((ReporteriaMovistarDbContext)context);
            return _DespachoEncabezadoEntities;
          }
        }

        public IEquipoScrapEntityRepository EquipoScrapEntities {
          get {
            if (_EquipoScrapEntities == null)
              _EquipoScrapEntities = new EquipoScrapEntityRepository((ReporteriaMovistarDbContext)context);
            return _EquipoScrapEntities;
          }
        }

        public IVWMovimientoEquipoEntityRepository VWMovimientoEquipoEntities {
          get {
            if (_VWMovimientoEquipoEntities == null)
              _VWMovimientoEquipoEntities = new VWMovimientoEquipoEntityRepository((ReporteriaMovistarDbContext)context);
            return _VWMovimientoEquipoEntities;
          }
        }

        public IOperarioEntityRepository OperarioEntities {
          get {
            if (_OperarioEntities == null)
              _OperarioEntities = new OperarioEntityRepository((ReporteriaMovistarDbContext)context);
            return _OperarioEntities;
          }
        }

        public ITempDespachoCsvEntityRepository TempDespachoCsvEntities {
          get {
            if (_TempDespachoCsvEntities == null)
              _TempDespachoCsvEntities = new TempDespachoCsvEntityRepository((ReporteriaMovistarDbContext)context);
            return _TempDespachoCsvEntities;
          }
        }

        public IApiUserEntityRepository ApiUserEntities {
          get {
            if (_ApiUserEntities == null)
              _ApiUserEntities = new ApiUserEntityRepository((ReporteriaMovistarDbContext)context);
            return _ApiUserEntities;
          }
        }

        public IEtapaSecuenciaEntityRepository EtapaSecuenciaEntities {
          get {
            if (_EtapaSecuenciaEntities == null)
              _EtapaSecuenciaEntities = new EtapaSecuenciaEntityRepository((ReporteriaMovistarDbContext)context);
            return _EtapaSecuenciaEntities;
          }
        }

        public ITempEquipoMovimientoCsvEntityRepository TempEquipoMovimientoCsvEntities {
          get {
            if (_TempEquipoMovimientoCsvEntities == null)
              _TempEquipoMovimientoCsvEntities = new TempEquipoMovimientoCsvEntityRepository((ReporteriaMovistarDbContext)context);
            return _TempEquipoMovimientoCsvEntities;
          }
        }

        public virtual void Save()
        {
            if (context == null)
                throw new InvalidOperationException("Context has not been initialized.");
            context.SaveChanges();
        }

        #endregion
    }
}
