//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: jue. 11 nov. 2021 9:55:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using ReporteriaMovistar.Domain.Interfaces.Repositories;

namespace ReporteriaMovistar.Infrastructure.Data.Repositories
{
    public partial class VWDetalleMovimientoEquipoPowerBiEntityRepository : EntityFrameworkRepository<ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity>, IVWDetalleMovimientoEquipoPowerBiEntityRepository
    {
        public VWDetalleMovimientoEquipoPowerBiEntityRepository(ReporteriaMovistar.Infrastructure.Data.DataProviders.ReporteriaMovistarDbContext context)
            : base(context)
        {
        }

        public virtual ICollection<ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual ReporteriaMovistar.Domain.Models.Entities.VWDetalleMovimientoEquipoPowerBiEntity GetByKey()
        {
            return null;
        }

        public new ReporteriaMovistar.Infrastructure.Data.DataProviders.ReporteriaMovistarDbContext Context 
        {
            get
            {
                return (ReporteriaMovistar.Infrastructure.Data.DataProviders.ReporteriaMovistarDbContext)base.Context;
            }
        }
    }
}
