//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 10-11-2021 01:36:07 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaClaro.Domain.Models.Entities;
using ReporteriaClaro.Domain.Models.Pagination;
using ReporteriaClaro.Domain.Models.Sorting;

namespace ReporteriaClaro.Domain.Interfaces.Repositories
{
    public partial interface IDespachoEstadoEntityRepository
    {
	    public Task<bool> ExistePosicionAsync(int position);

	    public Task BatchUpdatePosicionAsync(int position);

	    public Task<DespachoEstadoEntity> FindAsync(int id);

	    public Task<IEnumerable<DespachoEstadoEntity>> GetAsync();

	    public Task<PagedResult<DespachoEstadoEntity>> GetPaginadoAsync(bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
