//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 28-10-2021 03:52:54 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaClaro.Domain.Models.Entities;
using ReporteriaClaro.Domain.Models.Pagination;
using ReporteriaClaro.Domain.Models.Sorting;

namespace ReporteriaClaro.Domain.Interfaces.Repositories
{
    public partial interface IEquipoTecnologiaEntityRepository
    {
	    public Task<EquipoTecnologiaEntity> FindAsync(int id);

	    public Task<IEnumerable<EquipoTecnologiaEntity>> GetAsync();

	    public Task<PagedResult<EquipoTecnologiaEntity>> GetPaginadoAsync(bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
