//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 26-10-2021 03:18:16 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaClaro.Domain.Models.Entities;
using ReporteriaClaro.Domain.Models.Pagination;
using ReporteriaClaro.Domain.Models.Sorting;

namespace ReporteriaClaro.Domain.Interfaces.Repositories
{
    public partial interface IEtapaEntityRepository
    {
	    public Task<bool> ExistePosicionAsync(int position);

	    public Task BatchUpdatePosicionAsync(int position);

        public Task<EtapaEntity> FindConZonaAsync(int id);

        public Task<IEnumerable<EtapaEntity>> GetConZonaAsync();

        //public Task<IEnumerable<EtapaEntity>> GetListaEstadosPorIdsAsync(params int[] ids);

        public Task<PagedResult<EtapaEntity>> GetPaginadoAsync(bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
