//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 17-11-2021 10:40:58 AM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ReporteriaClaro.Domain.Models.Entities;
using ReporteriaClaro.Domain.Models.Pagination;
using ReporteriaClaro.Domain.Models.Sorting;

namespace ReporteriaClaro.Domain.Interfaces.Repositories
{
    public partial interface IOperarioEntityRepository
    {
	    public Task<OperarioEntity> FindAsync(int id);

	    public Task<IEnumerable<OperarioEntity>> GetTop20Async(string operarioBuscado);

	    public Task<PagedResult<OperarioEntity>> GetPaginadoAsync(bool activeRecords, PagerInfo pagerInfo, SortingInfo sortingInfo);
    }
}
