//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: jue. 11 nov. 2021 9:55:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ReporteriaClaro.Domain.Interfaces.Repositories
{
    public partial interface IVWDetalleMovimientoEquipoPowerBiEntityRepository
    {
    }
}
