//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 26-11-2021 12:45:31 PM
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ReporteriaMovistar.Clients.ApiPowerBi.Repositories.Interfaces;

namespace ReporteriaMovistar.Clients.ApiPowerBi.Repositories
{
    public partial class ApiUserEntityRepository
    {
	    public async Task<bool> ExistsKeyHashAsync(string keyHash)
	    {
		    return await this.objectSet.AnyAsync(e => e.Active && e.KeyHash == keyHash);
	    }
    }
}
