//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 03-12-2021 09:23:55 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using ReporteriaMovistar.Clients.ApiPowerBi.Repositories.Interfaces;

namespace ReporteriaMovistar.Clients.ApiPowerBi.Repositories
{
    public partial class VWUltimoEstadoEquipoPowerBiEntityRepository : EntityFrameworkRepository<ReporteriaMovistar.Clients.ApiPowerBi.Models.VWUltimoEstadoEquipoPowerBiEntity>, IVWUltimoEstadoEquipoPowerBiEntityRepository
    {
        public VWUltimoEstadoEquipoPowerBiEntityRepository(ReporteriaMovistar.Clients.ApiPowerBi.DataProviders.ReporteriaMovistarDbContext context)
            : base(context)
        {
        }

        public virtual ICollection<ReporteriaMovistar.Clients.ApiPowerBi.Models.VWUltimoEstadoEquipoPowerBiEntity> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual ReporteriaMovistar.Clients.ApiPowerBi.Models.VWUltimoEstadoEquipoPowerBiEntity GetByKey()
        {
            return null;
        }

        public new ReporteriaMovistar.Clients.ApiPowerBi.DataProviders.ReporteriaMovistarDbContext Context 
        {
            get
            {
                return (ReporteriaMovistar.Clients.ApiPowerBi.DataProviders.ReporteriaMovistarDbContext)base.Context;
            }
        }
    }
}
