//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 03-12-2021 09:23:53 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ReporteriaClaro.Clients.ApiPowerBi.Models
{
    public partial class VWEstadoLimpiezaPowerBiEntity {

        public virtual string Esn { get; set; }

        public virtual DateTime? FechaLimpieza { get; set; }

        public virtual string OperarioLimpieza { get; set; }

        public virtual DateTime? FechaRechazo { get; set; }

        public virtual string OperarioRechazo { get; set; }

        public virtual string Rechazado { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
