//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02-12-2021 12:12:47 PM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ReporteriaMovistar.Clients.ApiPowerBi.Repositories.Interfaces
{
    public partial interface IVWEstadoLimpiezaPowerBiEntityRepository
    {
    }
}
