//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 03-12-2021 09:23:55 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;

namespace ReporteriaClaro.Clients.ApiPowerBi.Repositories.Interfaces
{
    public partial interface IUnitOfWork : IDisposable
    {
        IApiUserEntityRepository ApiUserEntities { get; }
        IVWDetallePronosticoEquipoPowerBiEntityRepository VWDetallePronosticoEquipoPowerBiEntities { get; }
        IVWHistorialMovimientoEquipoPowerBiEntityRepository VWHistorialMovimientoEquipoPowerBiEntities { get; }
        IVWRechazoLimpiezaPowerBiEntityRepository VWRechazoLimpiezaPowerBiEntities { get; }
        IVWUltimoEstadoEquipoPowerBiEntityRepository VWUltimoEstadoEquipoPowerBiEntities { get; }
        IVWEstadoLimpiezaPowerBiEntityRepository VWEstadoLimpiezaPowerBiEntities { get; }
        void Save();
    }
}
