//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 01-12-2021 11:21:04 AM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ReporteriaClaro.Clients.ApiPowerBi.Repositories.Interfaces
{
    public partial interface IVWHistorialMovimientoEquipoPowerBiEntityRepository
    {
    }
}
