//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 10-12-2021 02:28:27 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ReporteriaClaro.Domain.Models.Entities
{
    public partial class IdentityUserEntity {

        public virtual string Id { get; set; }

        public virtual string FullName { get; set; }

        public virtual string NormalizedFullName { get; set; }

        public virtual DateTime CreatedAt { get; set; }

        public virtual string CreatedBy { get; set; }

        public virtual DateTime? ModifiedAt { get; set; }

        public virtual string ModifiedBy { get; set; }

        public virtual DateTime? DeactivatedAt { get; set; }

        public virtual string DeactivatedBy { get; set; }

        public virtual string Reason { get; set; }

        public virtual bool Active { get; set; }

        public virtual string UserName { get; set; }

        public virtual string NormalizedUserName { get; set; }

        public virtual string Email { get; set; }

        public virtual string NormalizedEmail { get; set; }

        public virtual bool EmailConfirmed { get; set; }

        public virtual string PasswordHash { get; set; }

        public virtual string SecurityStamp { get; set; }

        public virtual string ConcurrencyStamp { get; set; }

        public virtual string PhoneNumber { get; set; }

        public virtual bool PhoneNumberConfirmed { get; set; }

        public virtual bool TwoFactorEnabled { get; set; }

        public virtual DateTimeOffset? LockoutEnd { get; set; }

        public virtual bool LockoutEnabled { get; set; }

        public virtual int AccessFailedCount { get; set; }

        public virtual IList<IdentityUserAccessLogEntity> IdentityUserAccessLogEntities { get; set; }

        public virtual IList<IdentityUserClaimEntity> IdentityUserClaimEntities { get; set; }

        public virtual IList<IdentityUserExceptionLogEntity> IdentityUserExceptionLogEntities { get; set; }

        public virtual IList<IdentityUserLoginEntity> IdentityUserLoginEntities { get; set; }

        public virtual IList<IdentityUserOperationLogEntity> IdentityUserOperationLogEntities { get; set; }

        public virtual IList<IdentityUserRoleEntity> IdentityUserRoleEntities { get; set; }

        public virtual IList<IdentityUserTokenEntity> IdentityUserTokenEntities { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
